[
  {
    name: "Set de 2 Valijas 20 y 24 Pulgadas",
    code: "145-1002X2",
    brand: "Influencer",
    parentCategory: "Viajes",
    childCategory: "Valijas",
    price: "17475.32",
    imgUrl: "https://enchulate.com.ar/imagenes/productos/145_1002X2.jpg?v=1",
    quantity: 1,
    stock: [],
  },
  {
    name: "Set de Valijas x 2 unid",
    code: "1-26674",
    brand: "Head",
    parentCategory: "Viajes",
    childCategory: "Valijas",
    price: "11928.00",
    imgUrl: "https://enchulate.com.ar/imagenes/productos/1_26674.jpg?v=1",
    quantity: 2,
    stock: [],
  },
  {
    name: "Carry On",
    code: "1-26668",
    brand: "Discovery",
    parentCategory: "Viajes",
    childCategory: "Valijas",
    price: "8288.00",
    imgUrl: "https://enchulate.com.ar/imagenes/productos/1_26668.jpg?v=1",
    quantity: 1,
    stock: [],
  },
  {
    name: "Cubre Valijas",
    code: "10036",
    brand: "Travel Tech",
    parentCategory: "Viajes",
    childCategory: "Cubre valijas",
    price: "1250.00",
    imgUrl: "https://enchulate.com.ar/imagenes/productos/10036.jpg?v=1",
    quantity: "",
    stock: [
      { talle: "Negro", quantity: 4 },
      { talle: "Azul", quantity: 3 },
      { talle: "Multicolor", quantity: 5 },
    ],
  },
  {
    name: "Cubre Valijas",
    code: "10038",
    brand: "Travel Tech",
    parentCategory: "Viajes",
    childCategory: "Cubre valijas",
    price: "1250.00",
    imgUrl: "https://enchulate.com.ar/imagenes/productos/10038.jpg?v=1",
    quantity: "",
    stock: [
      { talle: "Blanco", quantity: 3 },
      { talle: "Fucsia", quantity: 2 },
      { talle: "Azul", quantity: 1 },
    ],
  },
  {
    name: "Cubre Valijas",
    code: "10039",
    brand: "Travel Tech",
    parentCategory: "Viajes",
    childCategory: "Cubre valijas",
    price: "1350.00",
    imgUrl: "https://enchulate.com.ar/imagenes/productos/10039.jpg?v=1",
    quantity: "",
    stock: [
      { talle: "Fucsia", quantity: 2 },
      { talle: "Blanco", quantity: 2 },
      { talle: "Azul", quantity: 1 },
    ],
  },
];
